### ISSUE TITLE
Crash in getScrollWH

### ISSUE THREAD

**Issue by wmertens** [react-component/tabs#113]
https://github.com/react-component/tabs/blob/2fd94c2034fca8a0165c53ce74b8b6dce360eb5b/src/ScrollableTabBarMixin.js#L96

This line crashed in one of our production apps, I presume that it was trying to reference an undefined node, perhaps because of not being loaded yet or being unmounted.

**Comment by yesmeck** [comment]
Could you provide a reproduction on https://codesandbox.io/

**Comment by wmertens** [comment]
:-/ Actually, I don't know how it triggers, and it might be difficult to find… all I know is that generally it works fine, but our automated error reporting got a stack trace from one of the website visitors at this location.

**Comment by yesmeck** [comment]
@wmertens I guess it was caused by the debounce tail call after component unmount.
