### ISSUE TITLE
this.cache 只在 didMount 时记录一次，导致参数变化时 cache 的数据不对

### ISSUE THREAD

**Issue by eternalsky** [react-component/tabs#121]
https://github.com/react-component/tabs/blob/master/src/SwipeableTabBarMixin.js#L97

如上，如果参数变化，比如 pageSize 或者 children 的数量发生变化，totalAvaliableDelta，tabWidth 这些参数都不会随之变化，造成新增加的 tab 不能 swipe 出来。

**Comment by LiangZugeng** [comment]
这个问题有Ant Design团队的人看一下吗？已经9天了。

**Comment by yesmeck** [comment]
> https://github.com/salt-ui/saltui/issues/178 就像引用的那个 issue 里一样，如果动态修改了 tabitem 的个数，比如从 11 个 变到 15 个，这样新增的 4 个，就划不出来

**Comment by LiangZugeng** [comment]
@yesmeck 看到你提交了一个commit，也就是说这个问题在在React-Component的tabs控件上已经修复了，那 @eternalsky 他们只需要引用最新的tabs控件就行了，对吧？

**Comment by yesmeck** [comment]
@LiangZugeng 还没发布，我验证下。
