### ISSUE TITLE
TypeError: Cannot read property 'ownerDocument' of undefined

### ISSUE THREAD

**Issue by hungnm10** [react-component/tabs#130]
When I deployed in dev environment, everything is good but I faced this issue when I tried to run my website in product environment. Please check this log and give me your help. Thank a lot.
react-dom.production.min.js:150 TypeError: Cannot read property 'ownerDocument' of undefined
    at a (InkTabBarNode.js:66)
    at i (InkTabBarNode.js:87)
    at t.value (InkTabBarNode.js:169)
    at commitLifeCycles (react-dom.production.min.js:158)
    at E (react-dom.production.min.js:184)
    at w (react-dom.production.min.js:181)
    at b (react-dom.production.min.js:180)
    at v (react-dom.production.min.js:180)
    at h (react-dom.production.min.js:179)
    at c (react-dom.production.min.js:178)

**Comment by terebentina** [comment]
This is happening to me too. The error doesn't appear in dev mode, only in production.
Using CRA with react 16.4.1 and rc tabs 9.3.1.
I downgraded tabs to 9.2.6 and this problem goes away.

Here's the stack trace:
![image](https://user-images.githubusercontent.com/238611/43036180-130484e2-8d05-11e8-8412-abe2fc4026ff.png)

**Comment by yinxin630** [comment]
I am the same problem. v2.9.4 is ok. v9.3.1 is error.
And this problem only appears on the production environment.

**Comment by hungnm10** [comment]
I downdgraded both 9.2.4 and 9.2.6 buy it's not working :(

**Comment by terebentina** [comment]
I stumbled upon this on 2 separate projects and for both the solution was to downgrade to exactly 9.2.6. @hungnm10 make sure you have exactly `"rc-tabs": "9.2.6",` in `package.json` and after that run `yarn` or `npm i` to have 9.2.6 installed.

**Comment by picodoth** [comment]
use https://github.com/react-component/tabs/pull/134 as a quick fix

**Comment by afc163** [comment]
close https://github.com/ant-design/ant-design/issues/11612
