### ISSUE TITLE
Type of top component "Tabs" exception in v5.9.1 

### ISSUE THREAD

**Issue by sixwinds** [react-component/tabs#16]
Hi yiminghe:

When I update rc-tabs from v5.7.0 to 5.9.1, I got React.createElement typ error: he first param of React.createElement should be a string or React Class( function ). So I console the top component Tabs like below:

```
let Tabs = require( 'rc-tabs' );
console.log( Tabs )
```

I got an Object , I suppose Tabs should be a React Class. I am not sure whether it is an issue. I refer to react official doc, and not find that React.createElement can accept an object as the first param.

ps:
I update my react to v15.0.2. I still got this exception. Below is error info in console:

> rctabletest.js:1014 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `App`.

> rctabletest.js:633 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `App`.

**Comment by giladbr** [comment]
Also not working for me - getting:

> Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of...

**Comment by yiminghe** [comment]
using es2015 export now,

```
var Tabs = require( 'rc-tabs' ).default? require( 'rc-tabs' ).default: require( 'rc-tabs' );
```
