### ISSUE TITLE
tabIndex="0"

### ISSUE THREAD

**Issue by simeiyu** [react-component/tabs#185]
tabIndex="0"，这个写在div标签上，真的让我很被动啊~怎么处理才能让他们变成-1呢？

**Comment by filipjnc** [comment]
This is part of a larger accessibility issue described here: https://github.com/ant-design/ant-design/issues/18798

**Comment by filipjnc** [comment]
Should be fixed when I finish the work on this pull request: https://github.com/react-component/tabs/pull/218

**Comment by dobrynin** [comment]
+1 I would appreciate this as well. Thanks @filipjnc!
