### ISSUE TITLE
Assign id attribute to tab pane element for automation purposes.

### ISSUE THREAD

**Issue by kfrajtak** [react-component/tabs#224]
Hi,
The `id` attribute is not available in props.
Also it would be good to use `key` value when provided (and `id` is not provided) to render as `id` attribute of the HTML element.
And also the `className` provided is not rendered.
Thanks,
Karel

See https://github.com/ant-design/ant-design/issues/11899

**Comment by filipjnc** [comment]
This is also needed for accessibility/screen reader to work properly. I included it on the list of this pull request: https://github.com/react-component/tabs/pull/218

My idea is to always use the key and append the id, if it's provided. Then we should recommend users to pass an unique id to the Tabs component, especially if there are two or more on the same page.
