### ISSUE TITLE
Module not found: Can't resolve 'rc-tabs/lib/ScrollableInkTabBar'

### ISSUE THREAD

**Issue by DishantDesai** [react-component/tabs#280]
In my project this error show 
version:11.3.1

can anyone help me with this?

**Comment by VimLeSai** [comment]
Please check this from some version of package ScrollableInkTabBar  and TabContent has been removed and there is no way that pacakage will work without it. 

@yiminghe @zombieJ 
Please check it once.

**Comment by VimLeSai** [comment]
It's happning version above 9.7.0

**Comment by zombieJ** [comment]
`rc-tabs@11.x` no need customize TabBar instead. You can follow new example for use `rc-tabs`. Or lock version to `10.x`
