### ISSUE TITLE
Force render content of tabs, not lazy render

### ISSUE THREAD

**Issue by zetoke** [react-component/tabs#29]
Hello!
Thanks for your great job and components!

How I can do forced render of content in tabs? Not lazy render after clicking on tabs.

**Comment by zetoke** [comment]
I created a pull request for this feature
#30

**Comment by yiminghe** [comment]
just rerender the whole tabs component

**Comment by zetoke** [comment]
But how I can do render of one tab, if I don't click on the tab?

**Comment by yiminghe** [comment]
you do not need to, it will render when needed

**Comment by zetoke** [comment]
But I need. I have some reusable complex component inside one of tab with heavy api work. So I want to force render one or two tabs to start working before click on it...

**Comment by zetoke** [comment]
@yiminghe so, can I reopen pull request? I really need it. And I think this is very useful customization (for a bit amount of cases).
I don't want to fork this component or use another like react-tabs (it has this type of customization).

**Comment by yiminghe** [comment]
support forceRender.

I suggest use action to do api work, not couple with ui

**Comment by zetoke** [comment]
@yiminghe Thanks a lot!

>I suggest use action to do api work, not couple with ui

Of course!
But I am on refactoring now. And I have some reusable parts, that have call stateless services with this api work. If I will start use actions, I will lost re-usability on this step.

**Comment by deathmood** [comment]
@yiminghe thank you very much for forceRender feature!! this is the main reason I'm using your tabs but not other.

BTW you've got an error in readme -- `forceUpdate` should be set on `TabPane` but not `TabContent`

**Comment by mariusbloemhof** [comment]
forceUpdate seems to no longer work since v4.0??
