### ISSUE TITLE
tab 切换时 TabPane 高度没有随里面内容高度的变化而变化

### ISSUE THREAD

**Issue by yesmeck** [react-component/tabs#35]
原来是这样的：

http://codepen.io/yesmeck/pen/PGRxAw

TabPane 的高度会随着里面内容的高度变化而变化。

7.0 后就变成这样了：

http://codepen.io/yesmeck/pen/JRLwPm

我用 `git bisect` 找了下，是在这个 https://github.com/react-component/tabs/commit/5a9b07bbdc27ef7ff096cd8cdfc045a2f45bc1cd commit 里改成这样的， 这是故意改成这样的吗？

**Comment by afc163** [comment]
应该是为了支持 antd-mobile 用了新的样式实现导致的。

**Comment by benjycui** [comment]
这个好像修复了？

**Comment by yesmeck** [comment]
修正了。

**Comment by yesmeck** [comment]
https://github.com/react-component/tabs/commit/6ad4e223798c72552a256c32168682541cf76bcb
