### ISSUE TITLE
Cannot read property 'getBoundingClientRect' of undefined

### ISSUE THREAD

**Issue by Triyugi** [react-component/tabs#44]
I am getting following error: 
`Tabs.js:118 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined(…)(anonymous function) @ Tabs.js:118`
`Tabs.js:118 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined(…)(anonymous function) @ Tabs.js:118`

**Comment by benjycui** [comment]
A re-producible online demo, please.

**Comment by paranoidjk** [comment]
close for no response.
