### ISSUE TITLE
关于 onTabClick 涉及的 key 类型定义的问题

### ISSUE THREAD

**Issue by theprimone** [react-component/tabs#447]
https://github.com/react-component/tabs/blob/master/src/TabNavList/index.tsx#L46
```ts
onTabClick: (activeKey: React.Key, e: React.MouseEvent | React.KeyboardEvent) => void;
```

https://github.com/react-component/tabs/blob/master/src/interface.ts#L37
```ts
onTabClick: (key: string, e: React.MouseEvent | React.KeyboardEvent) => void;
```

https://github.com/react-component/tabs/blob/master/src/Tabs.tsx#L70 `parseTabList` 函数将 key 转换为 string 类型，所以渲染时应该都是使用 string 类型的 key。这里想讨论两个问题：

1. `React.Key` 类型中 string 或者 number 都可以，为什么需要都转为 string 来处理呢？
2. 因为以上两个 `onTabClick` 函数定义不同，导致了使用 `renderTabBar` 时类型异常如下图：

![image](https://user-images.githubusercontent.com/18096089/143455987-7f316bc9-c993-424e-b01c-77553a532516.png)

目前如果只是修复 `renderTabBar` 的问题，修改很简单，此外是想了解为什么需要转换 key 的类型，如果不转的话看起来修改的地方就多了。

**Comment by zombieJ** [comment]
因为 `<Tab.Pane />` 是语法糖，React render 后会把 `key` 转成 `string`。也就是说我们在获取的时候就已经是转译后的 `string` 了，也因此无法判断源 `Key` 是什么类型。更好的方式是脱去 `key` 的关联，使用 `value` 等不会被 React 转译的 props。但是因为兼容性考虑，所以还是用的 `key`。

**Comment by theprimone** [comment]
@zombieJ 那 `onTabClick` 的类型问题修复一下？🤔

**Comment by theprimone** [comment]
`key` 转为 `string` 的[讨论](https://softwareengineering.stackexchange.com/a/432948)，对应 React 源码 https://github.com/facebook/react/blob/90e5d3638844414e1b9df0fe66c3fc46b211d210/packages/react/src/ReactElement.js#L224-L236

**Comment by theprimone** [comment]
v11.10.4 已修复
