### ISSUE TITLE
alpha 版本在 npm 被错误打上了 latest tag

### ISSUE THREAD

**Issue by stackia** [react-component/tabs#564]
<img width="820" alt="image" src="https://user-images.githubusercontent.com/5107241/183309247-8d1ac1eb-85d1-4c50-b546-cd6dabf096e1.png">

这会导致：
1. `npm install rc-tabs` 错误安装 alpha 版本
2. 对于有 dependabot 等自动依赖更新的项目，被意外更新到 alpha 版本

**Comment by afc163** [comment]
Fixed.
