### ISSUE TITLE
TabPane doesn't shown

### ISSUE THREAD

**Issue by Sheepeer** [react-component/tabs#574]
while` import {TabPane} from "rc-tabs"` causes no-this-module error, I used` import TabPane from "rc-tabs/lib/TabPanelList/TabPane"`, but it doesn't work at all.

Then I checked pull requests and find the new segment `items`, and I tried to use it, but it doesn't work as expected, the style seems not applied: 

my code of items:
```
      items: [
        {
          key: '1',
          label: 'test1',
          children: <div>test1</div>
        },
        {
          key: '2',
          label: 'test2',
          children: <div>test2</div>
        },
      ]
```

the result shown:
![image](https://user-images.githubusercontent.com/78125933/187648866-61181f4b-410f-4130-ad13-0bfc96bff287.png)

**Comment by Sheepeer** [comment]
I missed css file: `import "rc-tabs/assets/index.css"`

Can this be added to doc ? I didn't known css file should be imported after finishing reading the doc. 😢

**Comment by Chorer** [comment]
> I missed css file: `import "rc-tabs/assets/index.css"`
> 
> Can this be added to doc ? I didn't known css file should be imported after finishing reading the doc. 😢

It seems the author didn't want to update the doc at all. Even the demo is wrong.
