### ISSUE TITLE
tabListRef.current is null

### ISSUE THREAD

**Issue by taven-liu** [react-component/tabs#633]
```
// tabs/src/TabNavList/index.tsx
 const updateTabSizes = () =>
    setTabSizes(() => {
      const newSizes: TabSizeMap = new Map();
      tabs.forEach(({ key }) => {
        const btnNode = tabListRef.current.querySelector<HTMLElement>(`[data-node-key="${key}"]`);
        if (btnNode) {
          newSizes.set(key, {
            width: btnNode.offsetWidth,
            height: btnNode.offsetHeight,
            left: btnNode.offsetLeft,
            top: btnNode.offsetTop,
          });
        }
      });
      return newSizes;
    });
```
`tabListRef.current`为Null

**Comment by teamco** [comment]
The same issue (2 latest versions)

**Comment by taven-liu** [comment]
I have two Tabs inner and outer, when I change outer Tabs the inner Tabs will throw this error.
![image](https://user-images.githubusercontent.com/11688796/210025350-6bd419f1-3ca8-49b4-ba6b-47a5221bff83.png)

**Comment by GrigorM** [comment]
Anyone has found the cause of this? A fix? A workaround? I keep getting sporadically, and I'm not able to systematically reproduce it.

**Comment by taven-liu** [comment]
Upgrade Antd to last version to fix this issue
