### ISSUE TITLE
onTabClick 在Tabs 的 constructor中重复bind有3次。

### ISSUE THREAD

**Issue by hiddaorear** [react-component/tabs#79]
**onTabClick** 在Tabs 的 constructor中重复**bind**有3次。另外，什么时候用**HOC**重写这些代码？如有计划，我可以参与进来。

**Comment by paranoidjk** [comment]
will be fix in https://github.com/react-component/tabs/pull/76/files

**Comment by paranoidjk** [comment]
@hiddaorear Welcome PR.
