### ISSUE TITLE
getOffsetWH retrieve the wrong size

### ISSUE THREAD

**Issue by abramobagnara** [react-component/tabs#84]
In getOffsetWH instead to use offsetWidth/offsetHeight we should use scrollWidth/scrollHeight otherwise we get the wrong size for div.ant-tabs-nav leading to wrong scroll offset computation.

Tell me if you prefer a PR.

**Comment by paranoidjk** [comment]
Can you provide a reproducible demo?

**Comment by abramobagnara** [comment]
It is already in PR#85.
Note however that I've verified that if Input element has a specified width the bug is not triggered.

Compare https://codepen.io/abramo/pen/MvbVmV (showing the bug) with:
https://codepen.io/abramo/pen/xLerqz (where the bug is not triggered).

To see the bug just push enough times the plus button on the right.
