### ISSUE TITLE
Tabs.activeKeyIsValid must check if 'key' exist

### ISSUE THREAD

**Issue by sanchan** [react-component/tabs#88]
```
function activeKeyIsValid(props, key) {
  const keys = React.Children.map(props.children, child => child.key);
  return keys.indexOf(key) >= 0;
}
```

If the `children` contains a `non-object` child (null, false), the:

```
const keys = React.Children.map(props.children, child => child.key);
```

it's raising an error.

It should compact the children to remove `non-object` values.

I can create a PR for this.

**Comment by khankuan** [comment]
I have the same issue as well. @sanchan are you still going to tackle the bug?

**Comment by ColdXu** [comment]
9.0.3 报Uncaught (in promise) TypeError: Cannot read property 'key' of null
