### ISSUE TITLE
Wrong render TabPane

### ISSUE THREAD

**Issue by RostislavBerezhnoy** [react-component/tabs#89]
My code:
`````
<Tabs
    defaultActiveKey="1"
    tabBarPosition={"left"}
    renderTabBar={()=><ScrollableInkTabBar />}
    renderTabContent={()=><TabContent />}
    onChange={this.onChange}>

        <TabPane tab='tab 1' key="1">
           111111111
        </TabPane>

       <TabPane tab='tab 2' key="2">
           22222222
        </TabPane>
</Tabs>
`````

but i have:
![tab_err](https://user-images.githubusercontent.com/9082153/29066051-c6aedf28-7c36-11e7-9e43-3d6e8cba59bc.JPG)

How can i fix this? Thanks.

P.S. use rc-tabs@9.0.3

**Comment by paranoidjk** [comment]
http://react-component.github.io/tabs/examples/antd.html

The offcial demo works fine. Please provide a reproducible demo.

**Comment by benjycui** [comment]
Close for no response.
