### ISSUE TITLE
请问代码是用哪种方式打包构建的？

### ISSUE THREAD

**Issue by joexjx** [react-component/tabs#9]
您好，我分别用git和npm下载了tabs控件的代码，原以为git下载的应该是源码，然后用某种工具，如grunt或者glup来打包构建出前端可以引用的代码也就是npm install 出来的东西，可是当我打开两边的代码时，让我很困惑，到底是用哪种方式构建打包的，前端最后才能引用到，可能是我前端知识有限，所以请教一下您是用哪种方式打包构建的，git下载的代码和npm install的代码之间的关系是什么，npm install 完的代码我还要用哪种方式来引用，这样我前端才能用呢，谢谢。

**Comment by yiminghe** [comment]
webpack
