### ISSUE TITLE
glitch on mobile devices while try to scrolling

### ISSUE THREAD

**Issue by tOke3i** [react-component/tabs#98]
![glitch-on-mobile-devices](https://user-images.githubusercontent.com/16651056/29661924-38651f8a-88ce-11e7-9f67-0652929fd3a4.gif)

**Comment by tOke3i** [comment]
On my project this helps: 
const delta = e.srcEvent.type !== 'pointercancel' ? isVertical(this.props.tabBarPosition) ? e.deltaY : e.deltaX : 0;
on your examples it doesn't work. This bug is very important please try to fix it !

**Comment by tOke3i** [comment]
@afc163  @paranoidjk @yiminghe @dxq613

**Comment by tOke3i** [comment]
**var index = startIndex + **-deltaY** / viewSize;**
  if (index < 0) {
    index = Math.exp(index * RESISTANCE_COEF) - 1;
  } else if (index > maxIndex) {
    index = maxIndex + 1 - Math.exp((maxIndex - index) * RESISTANCE_COEF);
  }
  return index;
}

function getIndexByDelta(e) {
  **var delta = e.srcEvent.type !== "pointercancel" ? (0, _utils.isVertical)(this.props.tabBarPosition) ? e.deltaY : e.deltaX : 0;
  var deltaY = e.deltaY;**

**Comment by tOke3i** [comment]
this above fix it

**Comment by paranoidjk** [comment]
@tOke3i 

Can you confirm does this bug only happen in pc chrome browser? since i test in my iphone safari browser, is works fine.

And if you already have solution, PR is welcome.

**Comment by tOke3i** [comment]
It works fine on iPhone safari and chrome, for macOs canary works fine Mozilla and canary on android works fine! it has a bug on android chrome 59-60(itested only these versions)
The problem is that we fixed bug on finding the right delta шт in my previous PR, but when you use buttons to change tab sometimes the index of active tab is wrong and traslateX gives 100% more or less than we realy need, getIndexByDelta I think sometimes has bug but I couldn't find why... @paranoidjk

**Comment by tOke3i** [comment]
![glitch](https://user-images.githubusercontent.com/16651056/29920636-f2b091a2-8e56-11e7-94df-ba4792f8ab80.gif)

**Comment by paranoidjk** [comment]
cc @zhang740 is rewriting a rmc-tabs  from scratch.

**Comment by paranoidjk** [comment]
@tOke3i  Please wait for https://github.com/react-component/m-tabs
